# This file belongs to metrics in your profile.
# Create a GitHub access token (see below what perms it should provide).
# Uncomment "on" section to set up triggers for metrics updates.
# It is recommended to visit https://github.com/lowlighter/metrics#-documentation for full reference.
name: Metrics
on:
  # schedule: [{cron: "0 */6 * * *"}] # Schedule update
  workflow_dispatch: # Lines below let you run workflow manually and on each commit
  push: {branches: ["master", "main"]}
jobs:
  github-metrics:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: lowlighter/metrics@latest
        with:
          # Your GitHub token
          # The following scopes are required:
          #  - public_access (default scope)
          #  - repo
          #  - public_repo
          #  - read:project
          # The following additional scopes may be required:
          #  - read:org      (for organization related metrics)
          #  - read:user     (for user related data)
          #  - read:packages (for some packages related data)
          #  - repo          (optional, if you want to include private repositories)
          token: ${{ secrets.ACC_SECRET }}

          # Options
          user: EgorBron
          template: classic
          base: header, activity, community, repositories, metadata
          config_timezone: Europe/Moscow
          plugin_achievements: yes
          plugin_achievements_display: compact
          plugin_achievements_secrets: yes
          plugin_achievements_threshold: X
          #plugin_activity: yes
          #plugin_activity_days: 14
          #plugin_activity_filter: all
          #plugin_activity_limit: 10
          #plugin_activity_load: 300
          #plugin_activity_visibility: all
          plugin_gists: yes
          plugin_introduction: yes
          plugin_introduction_title: yes
          plugin_languages: yes
          plugin_languages_analysis_timeout: 15
          plugin_languages_categories: markup, programming
          plugin_languages_colors: github
          plugin_languages_limit: 50
          plugin_languages_other: no
          plugin_languages_recent_categories: markup, programming
          plugin_languages_recent_days: 14
          plugin_languages_recent_load: 300
          plugin_languages_sections: most-used
          plugin_languages_threshold: 0%
          plugin_projects: yes
          plugin_projects_limit: 5
          plugin_stars: yes
          plugin_stars_limit: 3
          plugin_traffic: yes
          repositories_forks: yes
          plugin_isocalendar: yes
          plugin_isocalendar_duration: full-year
          plugin_habits: yes
          plugin_habits_from: 1000
          plugin_habits_facts: yes
          #plugin_habits_charts: yes
          plugin_habits_trim: yes
          plugin_followup: yes
          plugin_followup_sections: user
